### ISSUE TITLE
Failed Bungeecord Notifications 

### ISSUE THREAD

**Issue by nicholasveronico** [MrTigreroux/TigerReports#128] opened 2022-12-15 01:05 UTC
Hello!

I am getting the following occasional error:

`[01:01:32 ERROR]: [TigerReports] An error has occurred when processing a BungeeCord notification:
java.lang.IllegalArgumentException: Invalid UUID string: null
        at java.util.UUID.fromString(UUID.java:215) ~[?:?]
        at fr.mrtigreroux.tigerreports.managers.BungeeManager.processPluginNotification(BungeeManager.java:867) ~[?:?]
        at fr.mrtigreroux.tigerreports.managers.BungeeManager.onPluginMessageReceived(BungeeManager.java:554) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:2477) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:39) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:18) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(SourceFile:52) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at org.imanity.imanityspigot.final .cD.run(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cB.executeTask(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cC.executeTask(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cB.executeNext(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.executeNext(SourceFile:1921) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cB.awaitTasks(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.sleepForTick(SourceFile:1894) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:831) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:829) [?:?]`

It happens only once after the server restarts when a staff member joins. 

Thanks in advance!

**Comment by MrTigreroux** [comment] 2022-12-18 10:46
Hi,

Thank you for reporting this error, I think that I found the cause and will fix it in the next version.

**Comment by MrTigreroux** [comment] 2022-12-18 12:21
This error should be fixed in the new [version 5.1.3](https://www.spigotmc.org/resources/tigerreports.25773/update?update=482476). Please tell me if it's not the case. Thank you again for reporting it.

**Closed** 2022-12-18 12:22 UTC
Labels: fixed ✔️
